config/routes.rb
Rails.application.routes.draw do
  resources :todo_lists do
    resources :todo_items
  end
  root "todo_lists#index"

end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :user
  validates :first_name, presence: true, unless: "last_name.present?"
  validates :last_name, presence: true, unless: "first_name.present?"
  validates :gender, inclusion: %w(male female)

  validate :notsue

  def notsue
  	if gender == "male" && first_name == "Sue"
  		errors.add(:base, "A male cannot be named Sue")
  	end
  end
  def self.get_all_profiles(min, max)
  	Profile.where("birth_year BETWEEN :min_year and :max_year", min_year: min, max_year: max).order("birth_year ASC")
  end
end

app/models/todo_item.rb
class TodoItem < ActiveRecord::Base
	belongs_to :todo_list
	default_scope { order :due_date}
end

app/models/todo_list.rb
class TodoList < ActiveRecord::Base
	belongs_to :user
	has_many :todo_items, dependent: :destroy
	default_scope { order :list_due_date}
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_one :profile, dependent: :destroy
	has_many :todo_lists, dependent: :destroy
	has_many :todo_items, through: :todo_lists, source: :todo_items
	validates :username, presence: true
	def get_completed_count
		self.todo_items.where(completed: true).count
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :set_todo_item, only: [:show, :edit, :update, :destroy]
  before_action :set_todo_list, only: [:create, :destroy]

  # GET /todo_items
  # GET /todo_items.json
  def index
    @todo_items = TodoItem.all
  end

  # GET /todo_items/1
  # GET /todo_items/1.json
  def show
  end

  # GET /todo_items/new
  def new
    @todo_item = TodoItem.new
  end

  # GET /todo_items/1/edit
  def edit
  end

  # POST /todo_items
  # POST /todo_items.json
  def create
    @todo_item = TodoItem.new(todo_item_params)

    respond_to do |format|
      if @todo_item.save
        format.html { redirect_to @todo_item, notice: 'Todo item was successfully created.' }
        format.json { render :show, status: :created, location: @todo_item }
      else
        format.html { render :new }
        format.json { render json: @todo_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_items/1
  # PATCH/PUT /todo_items/1.json
  def update
    respond_to do |format|
      if @todo_item.update(todo_item_params)
        format.html { redirect_to @todo_item, notice: 'Todo item was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_item }
      else
        format.html { render :edit }
        format.json { render json: @todo_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_items/1
  # DELETE /todo_items/1.json
  def destroy
    @todo_item.destroy
    respond_to do |format|
      format.html { redirect_to todo_items_url, notice: 'Todo item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_item
      @todo_item = TodoItem.find(params[:id])
    end

    def set_todo_list
      @todo_item = TodoItem.find(params[:id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_item_params
      params.require(:todo_item).permit(:title, :due_date, :description, :completed)
    end
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list, only: [:show, :edit, :update, :destroy]

  # GET /todo_lists
  # GET /todo_lists.json
  def index
    @todo_lists = TodoList.all
  end

  # GET /todo_lists/1
  # GET /todo_lists/1.json
  def show
  end

  # GET /todo_lists/new
  def new
    @todo_list = TodoList.new
  end

  # GET /todo_lists/1/edit
  def edit
  end

  # POST /todo_lists
  # POST /todo_lists.json
  def create
    @todo_list = TodoList.new(todo_list_params)

    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully created.' }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { render :new }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_lists/1
  # PATCH/PUT /todo_lists/1.json
  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1
  # DELETE /todo_lists/1.json
  def destroy
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to todo_lists_url, notice: 'Todo list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = TodoList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_list_params
      params.require(:todo_list).permit(:list_name, :list_due_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todolists</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/todo_items/_form.html.erb
<%= form_for(@todo_item) do |f| %>
  <% if @todo_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo_item.errors.count, "error") %> prohibited this todo_item from being saved:</h2>

      <ul>
      <% @todo_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :due_date %><br>
    <%= f.date_select :due_date %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :completed %><br>
    <%= f.check_box :completed %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todo_items/edit.html.erb
<h1>Editing Todo Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @todo_item %> |
<%= link_to 'Back', todo_items_path %>

app/views/todo_items/index.html.erb
<p id="notice"><%= notice %></p>

app/views/todo_items/new.html.erb
<h1>New Todo Item</h1>

<%= render 'form' %>

<%= link_to 'Back', todo_items_path %>

app/views/todo_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @todo_item.title %>
</p>

<p>
  <strong>Due date:</strong>
  <%= @todo_item.due_date %>
</p>

<p>
  <strong>Description:</strong>
  <%= @todo_item.description %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @todo_item.completed %>
</p>

<%= link_to 'Edit', edit_todo_item_path(@todo_item) %> |
<%= link_to 'Back', todo_items_path %>

app/views/todo_lists/_form.html.erb
<%= form_for(@todo_list) do |f| %>
  <% if @todo_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h2>

      <ul>
      <% @todo_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :list_name %><br>
    <%= f.text_field :list_name %>
  </div>
  <div class="field">
    <%= f.label :list_due_date %><br>
    <%= f.date_select :list_due_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todo_lists/edit.html.erb
<h1>Editing Todo List</h1>

<%= render 'form' %>

<%= link_to 'Show', @todo_list %> |
<%= link_to 'Back', todo_lists_path %>

app/views/todo_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Todo Lists</h1>

<table>
  <thead>
    <tr>
      <th>List name</th>
      <th>List due date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todo_lists.each do |todo_list| %>
      <tr>
        <td><%= todo_list.list_name %></td>
        <td><%= todo_list.list_due_date %></td>
        <td><%= link_to 'Show', todo_list %></td>
        <td><%= link_to 'Edit', edit_todo_list_path(todo_list) %></td>
        <td><%= link_to 'Destroy', todo_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Todo list', new_todo_list_path %>

app/views/todo_lists/new.html.erb
<h1>New Todo List</h1>

<%= render 'form' %>

<%= link_to 'Back', todo_lists_path %>

app/views/todo_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>List name:</strong>
  <%= @todo_list.list_name %>
</p>

<h1>Listing Todo Items</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Due date</th>
      <th>Description</th>
      <th>Completed</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @todo_list.todo_items.each do |todo_item| %>
      <tr>
        <td><%= todo_item.title %></td>
        <td><%= todo_item.due_date %></td>
        <td><%= todo_item.description %></td>
        <td><%= todo_item.completed %></td>
        <td><%= link_to 'Show', [@todo_list, todo_item] %></td>
        <td><%= link_to 'Destroy', [@todo_list, todo_item], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Todo Item', new_todo_list_todo_item_path(@todo_list.id) %>
<p>
  <strong>List due date:</strong>
  <%= @todo_list.list_due_date %>
</p>

<%= link_to 'Edit', edit_todo_list_path(@todo_list) %> |
<%= link_to 'Back', todo_lists_path %>